//LOGIN ACTION DISPATCH GLOBALS:

export const LOGIN_FETCHING = 'LOGIN_FETCHING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE =  'LOGIN_FAILURE';


//CREATE  USER ACTION DISPATCH GLOBALS:

export const POST_NEW_RV_USER = 'POST_NEW_RV_USER';
export const POST_NEW_RV_USER_SUCCESS = 'POST_NEW_RV_USER_SUCCESS';
export const POST_NEW_RV_USER_FAILURE = 'POST_NEW_RV_USER_FAILURE';

export const POST_NEW_LAND_USER = 'POST_NEW_LAND_USER';
export const POST_NEW_LAND_USER_SUCCESS = 'POST_NEW_LAND_USER_SUCCESS';
export const POST_NEW_LAND_USER_FAILURE = 'POST_NEW_LAND_USER_FAILURE';